const getQueryDoc = (table = "DOC_HCM_CLO") => {
  const query = `
    CREATE OR REPLACE TABLE \`${PROJECT_ID}.tmf_fwd_internal.${table}\` AS
    SELECT 
      CONCAT(IFNULL(x_ten_tau, ""), IFNULL(x_so_chuyen, ""), IFNULL(x_tuyen, ""), TRIM(IFNULL(x_so_cont, ""))) AS _pkId,
      x_chi_nhanh,
      x_id,
      x_ten_tau,
      x_so_chuyen,
      x_tuyen,
      x_pol,
      SAFE.PARSE_DATE('%d/%m/%Y',x_etd) AS x_etd,
      x_van_hanh_xuat,
      x_cust_handle,
      x_kinh_doanh,
      x_nhom,
      x_phap_nhan,
      x_khach_hang,
      x_mat_hang,
      x_hub,
      x_ptvc,
      x_20,
      x_40,
      x_40n,
      x_tai_trong,
      x_so_cont,
      x_so_seal,
      x_ty_le_ket_hop,
      x_bien_so_xe,
      x_thong_tin_xe_dong,
      x_ngay_dong,
      x_phuong_an_dong,
      x_ma_kho_dong_1,
      x_ma_kho_dong_2,
      x_ma_kho_dong_3,
      x_ten_kho_dong,
      x_dia_chi_kho_dong,
      x_phuong_xa_kho_dong,
      x_quan_huyen_kho_dong,
      x_tinh_dong,
      x_lien_he_kho_dong,
      x_nguoi_book_hang,
      x_ghi_chu_don_hang,
      x_tg_yeu_cau_den_kho,
      x_tg_du_kien_roi_kho,
      x_tg_du_kien_den_kho_trucking,
      x_tg_thuc_te_den_kho,
      x_tg_bat_dau_lam_hang,
      x_tg_thuc_te_roi_kho,
      x_vat_tu_dong_hang_1,
      x_so_luong_vat_tu_1,
      x_vat_tu_dong_hang_2,
      x_so_luong_vat_tu_2,
      x_vat_tu_dong_hang_3,
      x_so_luong_vat_tu_3,
      x_loai_cont_cap,
      x_kiem_dem,
      x_bao_hiem,
      x_so_lenh,
      x_noi_lay_rong,
      x_hub_ha_hang,
      x_ten_salan_dong,
      x_voy_salan_dong,
      x_etd_salan_dong,
      x_eta_salan_dong,
      x_dich_vu,
      x_ghi_chu_cho_van_hanh_nhap,
      x_luu_cont,
      x_phai_thu_vhx_chi_ho_kh,
      x_cuoc_tau_barem,
      x_giam_nhe,
      x_cuoc_db_theo_khach,
      x_giam_of_ha_lsip,
      x_cuoc_tau_thuc_tinh,
      x_seal,
      x_baf,
      x_lss,
      x_thc,
      x_lolo_pol,
      x_giam_lolo_pol,
      x_trucking_pol_khong_vat,
      x_trucking_pol_khong_vat_theo_pa_dong,
      x_neo_xe_khong_vat,
      x_cuoc_salan_pol,
      x_phi_boc_xep_co_vat,
      x_phi_boi_duong,
      x_phi_qua_tai_mooc,
      x_phi_mua_vat_tu_ngoai_job,
      x_phi_vat_tu_trong_job_co_vat,
      x_chi_phi_khac_co_vat,
      x_hoa_hong,
      x_kiem_dem_pol,
      x_du_phong,
      x_phi_quan_ly,
      x_phi_khac_vhx_chi_ho_kh,
      x_ghi_chu_vhx_chi_ho_kh,
      x_phi_khac_chi_ho_van_hanh,
      x_ghi_chu_phi_khac_chi_ho_van_hanh,
      dkn_eta,
      dkn_pod,
      dkn_hub_lay_hang,
      dkn_ghi_chu_cua_doc,
      dkn_so_bill,
      dkn_ngay_tinh_luu_bai,
      dkn_ngay_tra_hang,
      dkn_tg_yeu_cau_den_kho,
      dkn_tg_du_kien_roi_kho,
      dkn_kiem_dem,
      dkn_ma_kho_tra_du_kien_1,
      dkn_ma_kho_tra_du_kien_2,
      dkn_ma_kho_tra_du_kien_3,
      dkn_ten_kho_tra,
      dkn_dia_chi_kho_tra,
      dkn_phuong_xa,
      dkn_quan_huyen,
      dkn_tinh_tra,
      dkn_lien_he,
      dkn_gia_tri_hang_mua_bh,
      dkn_tien_mua_bh,
      dkn_cong_ty_bh,
      dkn_lua_chon,
      dkn_ty_le,
      dkn_cap_don,
      dkn_uy_quyen_gls, 
      SAFE_CAST(REPLACE(bthdk_tien_mat_du_kien, ',', '') AS FLOAT64) AS bthdk_tien_mat_du_kien,
      SAFE_CAST(REPLACE(bthdk_cong_no_du_kien, ',', '') AS FLOAT64) AS bthdk_cong_no_du_kien,
      SAFE_CAST(REPLACE(bthdk_luu_cont, ',', '') AS FLOAT64) AS bthdk_luu_cont,
      SAFE_CAST(REPLACE(bthdk_phi_local_charge, ',', '') AS FLOAT64) AS bthdk_phi_local_charge,
      SAFE_CAST(REPLACE(bthdk_phai_thu_vh_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phai_thu_vh_chi_ho_kh,
      SAFE_CAST(bthdk_doanh_thu_du_kien AS FLOAT64) as bthdk_doanh_thu_du_kien,
      SAFE_CAST(REPLACE(bthdk_cuoc_tau_barem, ',', '') AS FLOAT64) AS bthdk_cuoc_tau_barem,
      SAFE_CAST(REPLACE(bthdk_giam_nhe, ',', '') AS FLOAT64) AS bthdk_giam_nhe,
      SAFE_CAST(REPLACE(bthdk_cuoc_db, ',', '') AS FLOAT64) AS bthdk_cuoc_db,
      SAFE_CAST(REPLACE(bthdk_giam_of_ha_lsip, ',', '') AS FLOAT64) AS bthdk_giam_of_ha_lsip,
      SAFE_CAST(REPLACE(bthdk_cuoc_tau_thuc_tinh, ',', '') AS FLOAT64) AS bthdk_cuoc_tau_thuc_tinh,
      SAFE_CAST(REPLACE(bthdk_seal, ',', '') AS FLOAT64) AS bthdk_seal,
      SAFE_CAST(REPLACE(bthdk_baf, ',', '') AS FLOAT64) AS bthdk_baf,
      SAFE_CAST(REPLACE(bthdk_lss, ',', '') AS FLOAT64) AS bthdk_lss,
      SAFE_CAST(REPLACE(bthdk_thc, ',', '') AS FLOAT64) AS bthdk_thc,
      SAFE_CAST(REPLACE(bthdk_vsc, ',', '') AS FLOAT64) AS bthdk_vsc,
      SAFE_CAST(REPLACE(bthdk_phi_do, ',', '') AS FLOAT64) AS bthdk_phi_do,
      SAFE_CAST(REPLACE(bthdk_lolo_pol, ',', '') AS FLOAT64) AS bthdk_lolo_pol,
      SAFE_CAST(REPLACE(bthdk_giam_lolo_pol, ',', '') AS FLOAT64) AS bthdk_giam_lolo_pol,
      SAFE_CAST(REPLACE(bthdk_trucking_pol_khong_vat, ',', '') AS FLOAT64) AS bthdk_trucking_pol_khong_vat,
      SAFE_CAST(REPLACE(bthdk_trucking_pol_khong_vat_theo_pa_dong, ',', '') AS FLOAT64) AS bthdk_trucking_pol_khong_vat_theo_pa_dong,
      SAFE_CAST(REPLACE(bthdk_neo_xe_pol_khong_vat, ',', '') AS FLOAT64) AS bthdk_neo_xe_pol_khong_vat,
      SAFE_CAST(REPLACE(bthdk_kiem_dem_pol, ',', '') AS FLOAT64) AS bthdk_kiem_dem_pol,
      SAFE_CAST(REPLACE(bthdk_cuoc_salan_pol, ',', '') AS FLOAT64) AS bthdk_cuoc_salan_pol,
      SAFE_CAST(REPLACE(bthdk_phi_boc_xep_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_phi_boc_xep_co_vat_pol,
      SAFE_CAST(REPLACE(bthdk_phi_boi_duong_pol, ',', '') AS FLOAT64) AS bthdk_phi_boi_duong_pol,
      SAFE_CAST(REPLACE(bthdk_phi_qua_tai_mooc_pol, ',', '') AS FLOAT64) AS bthdk_phi_qua_tai_mooc_pol,
      SAFE_CAST(REPLACE(bthdk_phi_mua_vat_tu_ngoai_job_pol, ',', '') AS FLOAT64) AS bthdk_phi_mua_vat_tu_ngoai_job_pol,
      SAFE_CAST(REPLACE(bthdk_phi_vat_tu_trong_job_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_phi_vat_tu_trong_job_co_vat_pol,
      SAFE_CAST(REPLACE(bthdk_chi_phi_khac_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_chi_phi_khac_co_vat_pol,
      SAFE_CAST(REPLACE(bthdk_phi_khac_vhx_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phi_khac_vhx_chi_ho_kh,
      SAFE_CAST(REPLACE(bthdk_ghi_chu_vhx_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_ghi_chu_vhx_chi_ho_kh,
      SAFE_CAST(REPLACE(bthdk_lolo_pod, ',', '') AS FLOAT64) AS bthdk_lolo_pod,
      SAFE_CAST(REPLACE(bthdk_giam_lolo_pod, ',', '') AS FLOAT64) AS bthdk_giam_lolo_pod,
      SAFE_CAST(REPLACE(bthdk_trucking_pod_khong_vat, ',', '') AS FLOAT64) AS bthdk_trucking_pod_khong_vat,
      SAFE_CAST(REPLACE(bthdk_neo_xe_pod_khong_vat, ',', '') AS FLOAT64) AS bthdk_neo_xe_pod_khong_vat,
      SAFE_CAST(REPLACE(bthdk_cuoc_salan_pod, ',', '') AS FLOAT64) AS bthdk_cuoc_salan_pod,
      SAFE_CAST(REPLACE(bthdk_luu_cont_pod, ',', '') AS FLOAT64) AS bthdk_luu_cont_pod,
      SAFE_CAST(REPLACE(bthdk_phi_boc_xep_co_vat_pod, ',', '') AS FLOAT64) AS bthdk_phi_boc_xep_co_vat_pod,
      SAFE_CAST(REPLACE(REPLACE(bthdk_phi_boi_duong_pod, ',', ''),'Không chi','') AS FLOAT64) AS bthdk_phi_boi_duong_pod,
      SAFE_CAST(REPLACE(bthdk_phi_qua_tai_pod, ',', '') AS FLOAT64) AS bthdk_phi_qua_tai_pod,
      SAFE_CAST(REPLACE(bthdk_chi_phi_khac_co_vat_pod, ',', '') AS FLOAT64) AS bthdk_chi_phi_khac_co_vat_pod,
      SAFE_CAST(REPLACE(bthdk_phi_khac_vhn_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phi_khac_vhn_chi_ho_kh,
      SAFE_CAST(REPLACE(bthdk_ghi_chu_vhn_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_ghi_chu_vhn_chi_ho_kh,
      SAFE_CAST(REPLACE(bthdk_tien_bh, ',', '') AS FLOAT64) AS bthdk_tien_bh,
      SAFE_CAST(REPLACE(bthdk_hoa_hong, ',', '') AS FLOAT64) AS bthdk_hoa_hong,
      SAFE_CAST(REPLACE(bthdk_kiem_dem_pod, ',', '') AS FLOAT64) AS bthdk_kiem_dem_pod,
      SAFE_CAST(REPLACE(bthdk_du_phong, ',', '') AS FLOAT64) AS bthdk_du_phong,
      SAFE_CAST(REPLACE(bthdk_phi_quan_ly, ',', '') AS FLOAT64) AS bthdk_phi_quan_ly,
      bthdk_tong_chi_phi_du_kien,
      bthdk_hieu_qua_du_kien,
      SAFE_CAST(REPLACE(bthdk_ghi_chu_cong_no, ',', '') AS FLOAT64) AS bthdk_ghi_chu_cong_no,
      bthtt_ma_kho_tra_1,
      bthtt_ma_kho_tra_2,
      bthtt_ma_kho_tra_3,
      bthtt_ten_kho_tra,
      bthtt_dia_chi_kho_tra,
      bthtt_phuong_xa_kho_tra,
      bthtt_quan_huyen_kho_tra,
      bthtt_tinh_tra,
      bthtt_ngay_tra_hang,
      SAFE_CAST( REPLACE(bthtt_tien_mat_thuc_te,',','') AS FLOAT64) AS bthtt_tien_mat_thuc_te,
      SAFE_CAST( REPLACE(bthtt_cong_no_thuc_te,',','') AS FLOAT64) AS bthtt_cong_no_thuc_te,
      SAFE_CAST( REPLACE(bthtt_luu_cont,',','') AS FLOAT64) AS bthtt_luu_cont,
      SAFE_CAST( REPLACE(bthtt_phi_local_charge,',','') AS FLOAT64) AS bthtt_phi_local_charge,
      SAFE_CAST( REPLACE(bthtt_phai_thu_vh_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phai_thu_vh_chi_ho_kh,
      bthtt_doanh_thu_thuc_te,
      SAFE_CAST( REPLACE(bthtt_cuoc_tau_barem,',','') AS FLOAT64) AS bthtt_cuoc_tau_barem,
      SAFE_CAST( REPLACE(bthtt_giam_nhe,',','') AS FLOAT64) AS bthtt_giam_nhe,
      SAFE_CAST( REPLACE(bthtt_cuoc_db,',','') AS FLOAT64) AS bthtt_cuoc_db,
      SAFE_CAST( REPLACE(bthtt_giam_of_ha_lsip,',','') AS FLOAT64) AS bthtt_giam_of_ha_lsip,
      SAFE_CAST( REPLACE(bthtt_cuoc_tau_thuc_tinh,',','') AS FLOAT64) AS bthtt_cuoc_tau_thuc_tinh,
      SAFE_CAST( REPLACE(bthtt_seal,',','') AS FLOAT64) AS bthtt_seal,
      SAFE_CAST( REPLACE(bthtt_baf,',','') AS FLOAT64) AS bthtt_baf,
      SAFE_CAST( REPLACE(bthtt_lss,',','') AS FLOAT64) AS bthtt_lss,
      SAFE_CAST( REPLACE(bthtt_thc,',','') AS FLOAT64) AS bthtt_thc,
      SAFE_CAST( REPLACE(bthtt_vsc,',','') AS FLOAT64) AS bthtt_vsc,
      SAFE_CAST( REPLACE(bthtt_phi_do,',','') AS FLOAT64) AS bthtt_phi_do,
      SAFE_CAST( REPLACE(bthtt_lolo_pol,',','') AS FLOAT64) AS bthtt_lolo_pol,
      SAFE_CAST( REPLACE(bthtt_giam_lolo_pol,',','') AS FLOAT64) AS bthtt_giam_lolo_pol,
      SAFE_CAST( REPLACE(bthtt_trucking_pol_khong_vat,',','') AS FLOAT64) AS bthtt_trucking_pol_khong_vat,
      SAFE_CAST( REPLACE(bthtt_trucking_pol_khong_vat_theo_pa_dong,',','') AS FLOAT64) AS bthtt_trucking_pol_khong_vat_theo_pa_dong,
      SAFE_CAST( REPLACE(bthtt_neo_xe_pol_khong_vat,',','') AS FLOAT64) AS bthtt_neo_xe_pol_khong_vat,
      SAFE_CAST( REPLACE(bthtt_cuoc_salan_pol,',','') AS FLOAT64) AS bthtt_cuoc_salan_pol,
      SAFE_CAST( REPLACE(bthtt_phi_boc_xep_co_vat_pol,',','') AS FLOAT64) AS bthtt_phi_boc_xep_co_vat_pol,
      SAFE_CAST( REPLACE(bthtt_phi_vat_tu_trong_job_co_vat_pol,',','') AS FLOAT64) AS bthtt_phi_vat_tu_trong_job_co_vat_pol,
      SAFE_CAST( REPLACE(bthtt_chi_phi_khac_co_vat_pol,',','') AS FLOAT64) AS bthtt_chi_phi_khac_co_vat_pol,
      SAFE_CAST( REPLACE(bthtt_phi_khac_vhx_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phi_khac_vhx_chi_ho_kh,
      SAFE_CAST( REPLACE(bthtt_ghi_chu_vhx_chi_ho_kh,',','') AS FLOAT64) AS bthtt_ghi_chu_vhx_chi_ho_kh,
      SAFE_CAST( REPLACE(bthtt_lolo_pod,',','') AS FLOAT64) AS bthtt_lolo_pod,
      SAFE_CAST( REPLACE(bthtt_giam_lolo_pod,',','') AS FLOAT64) AS bthtt_giam_lolo_pod,
      SAFE_CAST( REPLACE(bthtt_trucking_pod_khong_vat,',','') AS FLOAT64) AS bthtt_trucking_pod_khong_vat,
      SAFE_CAST( REPLACE(bthtt_neo_xe_pod_khong_vat,',','') AS FLOAT64) AS bthtt_neo_xe_pod_khong_vat,
      SAFE_CAST( REPLACE(bthtt_cuoc_salan_pod,',','') AS FLOAT64) AS bthtt_cuoc_salan_pod,
      SAFE_CAST( REPLACE(bthtt_luu_cont_pod,',','') AS FLOAT64) AS bthtt_luu_cont_pod,
      SAFE_CAST( REPLACE(bthtt_phi_boc_xep_co_vat_pod,',','') AS FLOAT64) AS bthtt_phi_boc_xep_co_vat_pod,
      SAFE_CAST( REPLACE(bthtt_chi_phi_khac_co_vat_pod,',','') AS FLOAT64) AS bthtt_chi_phi_khac_co_vat_pod,
      SAFE_CAST( REPLACE(bthtt_phi_khac_vhn_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phi_khac_vhn_chi_ho_kh,
      SAFE_CAST( REPLACE(bthtt_ghi_chu_vhn_chi_ho_kh,',','') AS FLOAT64) AS bthtt_ghi_chu_vhn_chi_ho_kh,
      SAFE_CAST( REPLACE(bthtt_tien_bh,',','') AS FLOAT64) AS bthtt_tien_bh,
      SAFE_CAST( REPLACE(bthtt_phi_boi_duong_pol,',','') AS FLOAT64) AS bthtt_phi_boi_duong_pol,
      SAFE_CAST( REPLACE(bthtt_phi_qua_tai_mooc_pol,',','') AS FLOAT64) AS bthtt_phi_qua_tai_mooc_pol,
      SAFE_CAST( REPLACE(bthtt_phi_mua_vat_tu_ngoai_job_pol,',','') AS FLOAT64) AS bthtt_phi_mua_vat_tu_ngoai_job_pol,
      SAFE_CAST( REPLACE(REPLACE(bthtt_phi_boi_duong_pod,',',''),'Không chi','') AS FLOAT64) AS bthtt_phi_boi_duong_pod,
      SAFE_CAST( REPLACE(bthtt_phi_qua_tai_pod,',','') AS FLOAT64) AS bthtt_phi_qua_tai_pod,
      SAFE_CAST( REPLACE(bthtt_hoa_hong,',','') AS FLOAT64) AS bthtt_hoa_hong,
      SAFE_CAST( REPLACE(bthtt_kiem_dem_pol,',','') AS FLOAT64) AS bthtt_kiem_dem_pol,
      SAFE_CAST( REPLACE(bthtt_kiem_dem_pod,',','') AS FLOAT64) AS bthtt_kiem_dem_pod,
      SAFE_CAST( REPLACE(bthtt_du_phong,',','') AS FLOAT64) AS bthtt_du_phong,
      SAFE_CAST( REPLACE(bthtt_phi_quan_ly,',','') AS FLOAT64) AS bthtt_phi_quan_ly,
      bthtt_tong_chi_phi_thuc_te,
      bthtt_hieu_qua_thuc_te,
      n_ma_kho_tra_1,
      n_ma_kho_tra_2,
      n_ma_kho_tra_3,
      n_ten_kho_tra,
      n_dia_chi_kho_tra,
      n_phuong_xa_kho_tra,
      n_quan_huyen_kho_tra,
      n_tinh_tra,
      n_tien_mat_thu_khach,
      n_luu_cont_thu_khach,
      n_phi_local_charge,
      n_phai_thu_vh_chi_ho_kh,
      n_vsc,
      n_phi_do,
      n_lolo_pod,
      n_giam_lolo_pod,
      n_trucking_pod_khong_vat,
      n_neo_xe_pod_khong_vat,
      n_cuoc_salan_pod,
      n_luu_cont_pod,
      n_phi_boc_xep_co_vat_pod,
      n_phi_boi_duong_pod,
      n_phi_qua_tai_pod,
      n_chi_phi_khac_co_vat_pod,
      n_kiem_dem_pod,
      n_phi_du_phong,
      n_phi_khac_vhn_chi_ho_kh,
      n_ghi_chu_vhn_chi_ho_kh,
      n_phi_khac_chi_ho_van_hanh,
      n_ket_hop_sau_tra,
      cont_seal,
      ke_toan_phu_trach
      
    FROM \`${PROJECT_ID}.tmf_fwd_external.GS_${table}\`
    WHERE x_id IS NOT NULL;
  `
  return query
}

const queryTongDoc = `
  CREATE OR REPLACE TABLE \`tmf_fwd_internal.TONG_DOC\` AS
  WITH combined_data AS (
    SELECT * FROM \`tmf_fwd_internal.DOC_CLO\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_DAN\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_HCM_DAN\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_HCM_CLO\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_HCM_HPH\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_HPH\`
    UNION ALL
    SELECT * FROM \`tmf_fwd_internal.DOC_HCM_HPH_GAO_2025\`
  )
  SELECT 
    CONCAT(IFNULL(x_ten_tau, ""), IFNULL(x_so_chuyen, ""), IFNULL(x_tuyen, ""), TRIM(IFNULL(x_so_cont, ""))) AS _pkId,
    x_chi_nhanh,
    x_id,
    x_ten_tau,
    x_so_chuyen,
    x_tuyen,
    x_pol,
    SAFE.PARSE_DATE('%d/%m/%Y',x_etd) AS x_etd,
    x_van_hanh_xuat,
    x_cust_handle,
    x_kinh_doanh,
    x_nhom,
    x_phap_nhan,
    x_khach_hang,
    x_mat_hang,
    x_hub,
    x_ptvc,
    x_20,
    x_40,
    x_40n,
    x_tai_trong,
    x_so_cont,
    x_so_seal,
    x_ty_le_ket_hop,
    x_bien_so_xe,
    x_thong_tin_xe_dong,
    x_ngay_dong,
    x_phuong_an_dong,
    x_ma_kho_dong_1,
    x_ma_kho_dong_2,
    x_ma_kho_dong_3,
    x_ten_kho_dong,
    x_dia_chi_kho_dong,
    x_phuong_xa_kho_dong,
    x_quan_huyen_kho_dong,
    x_tinh_dong,
    x_lien_he_kho_dong,
    x_nguoi_book_hang,
    x_ghi_chu_don_hang,
    x_tg_yeu_cau_den_kho,
    x_tg_du_kien_roi_kho,
    x_tg_du_kien_den_kho_trucking,
    x_tg_thuc_te_den_kho,
    x_tg_bat_dau_lam_hang,
    x_tg_thuc_te_roi_kho,
    x_vat_tu_dong_hang_1,
    x_so_luong_vat_tu_1,
    x_vat_tu_dong_hang_2,
    x_so_luong_vat_tu_2,
    x_vat_tu_dong_hang_3,
    x_so_luong_vat_tu_3,
    x_loai_cont_cap,
    x_kiem_dem,
    x_bao_hiem,
    x_so_lenh,
    x_noi_lay_rong,
    x_hub_ha_hang,
    x_ten_salan_dong,
    x_voy_salan_dong,
    x_etd_salan_dong,
    x_eta_salan_dong,
    x_dich_vu,
    x_ghi_chu_cho_van_hanh_nhap,
    x_luu_cont,
    x_phai_thu_vhx_chi_ho_kh,
    x_cuoc_tau_barem,
    x_giam_nhe,
    x_cuoc_db_theo_khach,
    x_giam_of_ha_lsip,
    x_cuoc_tau_thuc_tinh,
    x_seal,
    x_baf,
    x_lss,
    x_thc,
    x_lolo_pol,
    x_giam_lolo_pol,
    x_trucking_pol_khong_vat,
    x_trucking_pol_khong_vat_theo_pa_dong,
    x_neo_xe_khong_vat,
    x_cuoc_salan_pol,
    x_phi_boc_xep_co_vat,
    x_phi_boi_duong,
    x_phi_qua_tai_mooc,
    x_phi_mua_vat_tu_ngoai_job,
    x_phi_vat_tu_trong_job_co_vat,
    x_chi_phi_khac_co_vat,
    x_hoa_hong,
    x_kiem_dem_pol,
    x_du_phong,
    x_phi_quan_ly,
    x_phi_khac_vhx_chi_ho_kh,
    x_ghi_chu_vhx_chi_ho_kh,
    x_phi_khac_chi_ho_van_hanh,
    x_ghi_chu_phi_khac_chi_ho_van_hanh,
    dkn_eta,
    dkn_pod,
    dkn_hub_lay_hang,
    dkn_ghi_chu_cua_doc,
    dkn_so_bill,
    dkn_ngay_tinh_luu_bai,
    dkn_ngay_tra_hang,
    dkn_tg_yeu_cau_den_kho,
    dkn_tg_du_kien_roi_kho,
    dkn_kiem_dem,
    dkn_ma_kho_tra_du_kien_1,
    dkn_ma_kho_tra_du_kien_2,
    dkn_ma_kho_tra_du_kien_3,
    dkn_ten_kho_tra,
    dkn_dia_chi_kho_tra,
    dkn_phuong_xa,
    dkn_quan_huyen,
    dkn_tinh_tra,
    dkn_lien_he,
    dkn_gia_tri_hang_mua_bh,
    dkn_tien_mua_bh,
    dkn_cong_ty_bh,
    dkn_lua_chon,
    dkn_ty_le,
    dkn_cap_don,
    dkn_uy_quyen_gls, 
    SAFE_CAST(REPLACE(bthdk_tien_mat_du_kien, ',', '') AS FLOAT64) AS bthdk_tien_mat_du_kien,
    SAFE_CAST(REPLACE(bthdk_cong_no_du_kien, ',', '') AS FLOAT64) AS bthdk_cong_no_du_kien,
    SAFE_CAST(REPLACE(bthdk_luu_cont, ',', '') AS FLOAT64) AS bthdk_luu_cont,
    SAFE_CAST(REPLACE(bthdk_phi_local_charge, ',', '') AS FLOAT64) AS bthdk_phi_local_charge,
    SAFE_CAST(REPLACE(bthdk_phai_thu_vh_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phai_thu_vh_chi_ho_kh,
    SAFE_CAST(bthdk_doanh_thu_du_kien AS FLOAT64) as bthdk_doanh_thu_du_kien,
    SAFE_CAST(REPLACE(bthdk_cuoc_tau_barem, ',', '') AS FLOAT64) AS bthdk_cuoc_tau_barem,
    SAFE_CAST(REPLACE(bthdk_giam_nhe, ',', '') AS FLOAT64) AS bthdk_giam_nhe,
    SAFE_CAST(REPLACE(bthdk_cuoc_db, ',', '') AS FLOAT64) AS bthdk_cuoc_db,
    SAFE_CAST(REPLACE(bthdk_giam_of_ha_lsip, ',', '') AS FLOAT64) AS bthdk_giam_of_ha_lsip,
    SAFE_CAST(REPLACE(bthdk_cuoc_tau_thuc_tinh, ',', '') AS FLOAT64) AS bthdk_cuoc_tau_thuc_tinh,
    SAFE_CAST(REPLACE(bthdk_seal, ',', '') AS FLOAT64) AS bthdk_seal,
    SAFE_CAST(REPLACE(bthdk_baf, ',', '') AS FLOAT64) AS bthdk_baf,
    SAFE_CAST(REPLACE(bthdk_lss, ',', '') AS FLOAT64) AS bthdk_lss,
    SAFE_CAST(REPLACE(bthdk_thc, ',', '') AS FLOAT64) AS bthdk_thc,
    SAFE_CAST(REPLACE(bthdk_vsc, ',', '') AS FLOAT64) AS bthdk_vsc,
    SAFE_CAST(REPLACE(bthdk_phi_do, ',', '') AS FLOAT64) AS bthdk_phi_do,
    SAFE_CAST(REPLACE(bthdk_lolo_pol, ',', '') AS FLOAT64) AS bthdk_lolo_pol,
    SAFE_CAST(REPLACE(bthdk_giam_lolo_pol, ',', '') AS FLOAT64) AS bthdk_giam_lolo_pol,
    SAFE_CAST(REPLACE(bthdk_trucking_pol_khong_vat, ',', '') AS FLOAT64) AS bthdk_trucking_pol_khong_vat,
    SAFE_CAST(REPLACE(bthdk_trucking_pol_khong_vat_theo_pa_dong, ',', '') AS FLOAT64) AS bthdk_trucking_pol_khong_vat_theo_pa_dong,
    SAFE_CAST(REPLACE(bthdk_neo_xe_pol_khong_vat, ',', '') AS FLOAT64) AS bthdk_neo_xe_pol_khong_vat,
    SAFE_CAST(REPLACE(bthdk_kiem_dem_pol, ',', '') AS FLOAT64) AS bthdk_kiem_dem_pol,
    SAFE_CAST(REPLACE(bthdk_cuoc_salan_pol, ',', '') AS FLOAT64) AS bthdk_cuoc_salan_pol,
    SAFE_CAST(REPLACE(bthdk_phi_boc_xep_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_phi_boc_xep_co_vat_pol,
    SAFE_CAST(REPLACE(bthdk_phi_boi_duong_pol, ',', '') AS FLOAT64) AS bthdk_phi_boi_duong_pol,
    SAFE_CAST(REPLACE(bthdk_phi_qua_tai_mooc_pol, ',', '') AS FLOAT64) AS bthdk_phi_qua_tai_mooc_pol,
    SAFE_CAST(REPLACE(bthdk_phi_mua_vat_tu_ngoai_job_pol, ',', '') AS FLOAT64) AS bthdk_phi_mua_vat_tu_ngoai_job_pol,
    SAFE_CAST(REPLACE(bthdk_phi_vat_tu_trong_job_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_phi_vat_tu_trong_job_co_vat_pol,
    SAFE_CAST(REPLACE(bthdk_chi_phi_khac_co_vat_pol, ',', '') AS FLOAT64) AS bthdk_chi_phi_khac_co_vat_pol,
    SAFE_CAST(REPLACE(bthdk_phi_khac_vhx_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phi_khac_vhx_chi_ho_kh,
    SAFE_CAST(REPLACE(bthdk_ghi_chu_vhx_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_ghi_chu_vhx_chi_ho_kh,
    SAFE_CAST(REPLACE(bthdk_lolo_pod, ',', '') AS FLOAT64) AS bthdk_lolo_pod,
    SAFE_CAST(REPLACE(bthdk_giam_lolo_pod, ',', '') AS FLOAT64) AS bthdk_giam_lolo_pod,
    SAFE_CAST(REPLACE(bthdk_trucking_pod_khong_vat, ',', '') AS FLOAT64) AS bthdk_trucking_pod_khong_vat,
    SAFE_CAST(REPLACE(bthdk_neo_xe_pod_khong_vat, ',', '') AS FLOAT64) AS bthdk_neo_xe_pod_khong_vat,
    SAFE_CAST(REPLACE(bthdk_cuoc_salan_pod, ',', '') AS FLOAT64) AS bthdk_cuoc_salan_pod,
    SAFE_CAST(REPLACE(bthdk_luu_cont_pod, ',', '') AS FLOAT64) AS bthdk_luu_cont_pod,
    SAFE_CAST(REPLACE(bthdk_phi_boc_xep_co_vat_pod, ',', '') AS FLOAT64) AS bthdk_phi_boc_xep_co_vat_pod,
    SAFE_CAST(REPLACE(REPLACE(bthdk_phi_boi_duong_pod, ',', ''),'Không chi','') AS FLOAT64) AS bthdk_phi_boi_duong_pod,
    SAFE_CAST(REPLACE(bthdk_phi_qua_tai_pod, ',', '') AS FLOAT64) AS bthdk_phi_qua_tai_pod,
    SAFE_CAST(REPLACE(bthdk_chi_phi_khac_co_vat_pod, ',', '') AS FLOAT64) AS bthdk_chi_phi_khac_co_vat_pod,
    SAFE_CAST(REPLACE(bthdk_phi_khac_vhn_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_phi_khac_vhn_chi_ho_kh,
    SAFE_CAST(REPLACE(bthdk_ghi_chu_vhn_chi_ho_kh, ',', '') AS FLOAT64) AS bthdk_ghi_chu_vhn_chi_ho_kh,
    SAFE_CAST(REPLACE(bthdk_tien_bh, ',', '') AS FLOAT64) AS bthdk_tien_bh,
    SAFE_CAST(REPLACE(bthdk_hoa_hong, ',', '') AS FLOAT64) AS bthdk_hoa_hong,
    SAFE_CAST(REPLACE(bthdk_kiem_dem_pod, ',', '') AS FLOAT64) AS bthdk_kiem_dem_pod,
    SAFE_CAST(REPLACE(bthdk_du_phong, ',', '') AS FLOAT64) AS bthdk_du_phong,
    SAFE_CAST(REPLACE(bthdk_phi_quan_ly, ',', '') AS FLOAT64) AS bthdk_phi_quan_ly,
    bthdk_tong_chi_phi_du_kien,
    bthdk_hieu_qua_du_kien,
    SAFE_CAST(REPLACE(bthdk_ghi_chu_cong_no, ',', '') AS FLOAT64) AS bthdk_ghi_chu_cong_no,
    bthtt_ma_kho_tra_1,
    bthtt_ma_kho_tra_2,
    bthtt_ma_kho_tra_3,
    bthtt_ten_kho_tra,
    bthtt_dia_chi_kho_tra,
    bthtt_phuong_xa_kho_tra,
    bthtt_quan_huyen_kho_tra,
    bthtt_tinh_tra,
    bthtt_ngay_tra_hang,
    SAFE_CAST( REPLACE(bthtt_tien_mat_thuc_te,',','') AS FLOAT64) AS bthtt_tien_mat_thuc_te,
    SAFE_CAST( REPLACE(bthtt_cong_no_thuc_te,',','') AS FLOAT64) AS bthtt_cong_no_thuc_te,
    SAFE_CAST( REPLACE(bthtt_luu_cont,',','') AS FLOAT64) AS bthtt_luu_cont,
    SAFE_CAST( REPLACE(bthtt_phi_local_charge,',','') AS FLOAT64) AS bthtt_phi_local_charge,
    SAFE_CAST( REPLACE(bthtt_phai_thu_vh_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phai_thu_vh_chi_ho_kh,
    bthtt_doanh_thu_thuc_te,
    SAFE_CAST( REPLACE(bthtt_cuoc_tau_barem,',','') AS FLOAT64) AS bthtt_cuoc_tau_barem,
    SAFE_CAST( REPLACE(bthtt_giam_nhe,',','') AS FLOAT64) AS bthtt_giam_nhe,
    SAFE_CAST( REPLACE(bthtt_cuoc_db,',','') AS FLOAT64) AS bthtt_cuoc_db,
    SAFE_CAST( REPLACE(bthtt_giam_of_ha_lsip,',','') AS FLOAT64) AS bthtt_giam_of_ha_lsip,
    SAFE_CAST( REPLACE(bthtt_cuoc_tau_thuc_tinh,',','') AS FLOAT64) AS bthtt_cuoc_tau_thuc_tinh,
    SAFE_CAST( REPLACE(bthtt_seal,',','') AS FLOAT64) AS bthtt_seal,
    SAFE_CAST( REPLACE(bthtt_baf,',','') AS FLOAT64) AS bthtt_baf,
    SAFE_CAST( REPLACE(bthtt_lss,',','') AS FLOAT64) AS bthtt_lss,
    SAFE_CAST( REPLACE(bthtt_thc,',','') AS FLOAT64) AS bthtt_thc,
    SAFE_CAST( REPLACE(bthtt_vsc,',','') AS FLOAT64) AS bthtt_vsc,
    SAFE_CAST( REPLACE(bthtt_phi_do,',','') AS FLOAT64) AS bthtt_phi_do,
    SAFE_CAST( REPLACE(bthtt_lolo_pol,',','') AS FLOAT64) AS bthtt_lolo_pol,
    SAFE_CAST( REPLACE(bthtt_giam_lolo_pol,',','') AS FLOAT64) AS bthtt_giam_lolo_pol,
    SAFE_CAST( REPLACE(bthtt_trucking_pol_khong_vat,',','') AS FLOAT64) AS bthtt_trucking_pol_khong_vat,
    SAFE_CAST( REPLACE(bthtt_trucking_pol_khong_vat_theo_pa_dong,',','') AS FLOAT64) AS bthtt_trucking_pol_khong_vat_theo_pa_dong,
    SAFE_CAST( REPLACE(bthtt_neo_xe_pol_khong_vat,',','') AS FLOAT64) AS bthtt_neo_xe_pol_khong_vat,
    SAFE_CAST( REPLACE(bthtt_cuoc_salan_pol,',','') AS FLOAT64) AS bthtt_cuoc_salan_pol,
    SAFE_CAST( REPLACE(bthtt_phi_boc_xep_co_vat_pol,',','') AS FLOAT64) AS bthtt_phi_boc_xep_co_vat_pol,
    SAFE_CAST( REPLACE(bthtt_phi_vat_tu_trong_job_co_vat_pol,',','') AS FLOAT64) AS bthtt_phi_vat_tu_trong_job_co_vat_pol,
    SAFE_CAST( REPLACE(bthtt_chi_phi_khac_co_vat_pol,',','') AS FLOAT64) AS bthtt_chi_phi_khac_co_vat_pol,
    SAFE_CAST( REPLACE(bthtt_phi_khac_vhx_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phi_khac_vhx_chi_ho_kh,
    SAFE_CAST( REPLACE(bthtt_ghi_chu_vhx_chi_ho_kh,',','') AS FLOAT64) AS bthtt_ghi_chu_vhx_chi_ho_kh,
    SAFE_CAST( REPLACE(bthtt_lolo_pod,',','') AS FLOAT64) AS bthtt_lolo_pod,
    SAFE_CAST( REPLACE(bthtt_giam_lolo_pod,',','') AS FLOAT64) AS bthtt_giam_lolo_pod,
    SAFE_CAST( REPLACE(bthtt_trucking_pod_khong_vat,',','') AS FLOAT64) AS bthtt_trucking_pod_khong_vat,
    SAFE_CAST( REPLACE(bthtt_neo_xe_pod_khong_vat,',','') AS FLOAT64) AS bthtt_neo_xe_pod_khong_vat,
    SAFE_CAST( REPLACE(bthtt_cuoc_salan_pod,',','') AS FLOAT64) AS bthtt_cuoc_salan_pod,
    SAFE_CAST( REPLACE(bthtt_luu_cont_pod,',','') AS FLOAT64) AS bthtt_luu_cont_pod,
    SAFE_CAST( REPLACE(bthtt_phi_boc_xep_co_vat_pod,',','') AS FLOAT64) AS bthtt_phi_boc_xep_co_vat_pod,
    SAFE_CAST( REPLACE(bthtt_chi_phi_khac_co_vat_pod,',','') AS FLOAT64) AS bthtt_chi_phi_khac_co_vat_pod,
    SAFE_CAST( REPLACE(bthtt_phi_khac_vhn_chi_ho_kh,',','') AS FLOAT64) AS bthtt_phi_khac_vhn_chi_ho_kh,
    SAFE_CAST( REPLACE(bthtt_ghi_chu_vhn_chi_ho_kh,',','') AS FLOAT64) AS bthtt_ghi_chu_vhn_chi_ho_kh,
    SAFE_CAST( REPLACE(bthtt_tien_bh,',','') AS FLOAT64) AS bthtt_tien_bh,
    SAFE_CAST( REPLACE(bthtt_phi_boi_duong_pol,',','') AS FLOAT64) AS bthtt_phi_boi_duong_pol,
    SAFE_CAST( REPLACE(bthtt_phi_qua_tai_mooc_pol,',','') AS FLOAT64) AS bthtt_phi_qua_tai_mooc_pol,
    SAFE_CAST( REPLACE(bthtt_phi_mua_vat_tu_ngoai_job_pol,',','') AS FLOAT64) AS bthtt_phi_mua_vat_tu_ngoai_job_pol,
    SAFE_CAST( REPLACE(REPLACE(bthtt_phi_boi_duong_pod,',',''),'Không chi','') AS FLOAT64) AS bthtt_phi_boi_duong_pod,
    SAFE_CAST( REPLACE(bthtt_phi_qua_tai_pod,',','') AS FLOAT64) AS bthtt_phi_qua_tai_pod,
    SAFE_CAST( REPLACE(bthtt_hoa_hong,',','') AS FLOAT64) AS bthtt_hoa_hong,
    SAFE_CAST( REPLACE(bthtt_kiem_dem_pol,',','') AS FLOAT64) AS bthtt_kiem_dem_pol,
    SAFE_CAST( REPLACE(bthtt_kiem_dem_pod,',','') AS FLOAT64) AS bthtt_kiem_dem_pod,
    SAFE_CAST( REPLACE(bthtt_du_phong,',','') AS FLOAT64) AS bthtt_du_phong,
    SAFE_CAST( REPLACE(bthtt_phi_quan_ly,',','') AS FLOAT64) AS bthtt_phi_quan_ly,
    bthtt_tong_chi_phi_thuc_te,
    bthtt_hieu_qua_thuc_te,
    n_ma_kho_tra_1,
    n_ma_kho_tra_2,
    n_ma_kho_tra_3,
    n_ten_kho_tra,
    n_dia_chi_kho_tra,
    n_phuong_xa_kho_tra,
    n_quan_huyen_kho_tra,
    n_tinh_tra,
    n_tien_mat_thu_khach,
    n_luu_cont_thu_khach,
    n_phi_local_charge,
    n_phai_thu_vh_chi_ho_kh,
    n_vsc,
    n_phi_do,
    n_lolo_pod,
    n_giam_lolo_pod,
    n_trucking_pod_khong_vat,
    n_neo_xe_pod_khong_vat,
    n_cuoc_salan_pod,
    n_luu_cont_pod,
    n_phi_boc_xep_co_vat_pod,
    n_phi_boi_duong_pod,
    n_phi_qua_tai_pod,
    n_chi_phi_khac_co_vat_pod,
    n_kiem_dem_pod,
    n_phi_du_phong,
    n_phi_khac_vhn_chi_ho_kh,
    n_ghi_chu_vhn_chi_ho_kh,
    n_phi_khac_chi_ho_van_hanh,
    n_ket_hop_sau_tra,
    cont_seal,
    ke_toan_phu_trach
  FROM combined_data WHERE x_khach_hang IS NOT NULL
  UNION ALL
  SELECT * FROM \`tmf_fwd_internal.TONG_DOC_HISTORY\`;
`

// const queryTongDoc = `
//   CREATE OR REPLACE TABLE \`${PROJECT_ID}.tmf_fwd_internal.TONG_DOC\` AS
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_CLO\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_DAN\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_HPH\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_HCM_CLO\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_HCM_DAN\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_HCM_HPH\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.DOC_HCM_HPH_GAO_2025\`
//   UNION ALL
//   SELECT * FROM \`${PROJECT_ID}.tmf_fwd_internal.TONG_DOC_HISTORY\`
// `
