const COL_ACTIVE = 1
const COL_REFRESH_RATE = 2
const COL_TEN = 3
const COL_URL = 4
const COL_ID = 5
const COL_NGAY_GIO_SUA = 6
const COL_ID_SUA = 7
const COL_LAM_MOI_BIGQUERY = 8
const COL_DEM_LAM_MOI = 9
const COL_DATASET_BIGQUERY = 10
const COL_TABLE_BIGQUERY = 11
const COL_QUERY_CHA_BIGQUERY = 12
const COL_QUERY_CON_BIGQUERY = 13
const COL_LAST_RUN = 14

// Column Index
const CI = {
  ACTIVE: 0,
  REFRESH_RATE: 1,
  TEN: 2,
  URL: 3,
  ID: 4,
  NGAY_GIO_SUA: 5,
  ID_SUA: 6,
  LAM_MOI_BIGQUERY: 7,
  DEM_LAM_MOI: 8,
  DATASET_BIGQUERY: 9,
  TABLE_BIGQUERY: 10,
  QUERY_CHA_BIGQUERY: 11,
  QUERY_CON_BIGQUERY: 12,
  LAST_RUN: 13,
}